/*
 * Copyright (c) 2005 Torbjšrn Gannholm
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 */
package net.homelinux.tobe.weffo;

import junit.framework.TestCase;

import javax.xml.transform.Source;
import javax.xml.transform.Result;
import javax.xml.transform.URIResolver;
import javax.xml.transform.TransformerException;
import javax.xml.transform.stream.StreamSource;
import javax.xml.transform.stream.StreamResult;
import java.io.StringReader;
import java.io.StringWriter;
import java.util.Map;
import java.util.HashMap;

/**
 * Test the weffo-pi p-i <?weffo-pi name XPathSelector?>.
 * The use of string comparisons is not perfect, and may fail for some implementations of parsers/transformers.
 */
public class ProcessingInstructionTest extends TestCase {
    String model = "<model test=\"Test\"><data>Value</data><type>String</type><repeat id=\"1\">first</repeat><repeat id=\"2\">second</repeat></model>";

    public void testPI() {
        String view = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<?weffo-param myParam=default?>" +
                "<?weffo-pi xml-stylesheet document($myParam)/prefs/stylesheet?>" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\" w:text=\"document($myParam)/pref\"></view>";
        String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<!--Generated by weffo version "+Weffo.VERSION+"-->" +
                "<?xml-stylesheet href='skin.css' type='text/css'?>\n" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"/>";
        Source modelSource = new StreamSource(new StringReader(model));
        Source viewSource = new StreamSource(new StringReader(view));
        StringWriter result = new StringWriter();
        Result xslResult = new StreamResult(result);
        try {
            Map params = new HashMap();
            params.put("myParam", "urn:prefs");
            URIResolver uriResolver = new URIResolver() {
                String userPrefs = "<prefs><user>me</user><stylesheet>href='skin.css' type='text/css'</stylesheet></prefs>";

                public Source resolve(String uri, String base) throws TransformerException {
                    return new StreamSource(new StringReader(userPrefs));
                }
            };
            Weffo.outputFromPrototype(viewSource, modelSource, xslResult,params, uriResolver);
        } catch (TransformerException e) {
            e.printStackTrace();
        }
        String out = result.toString();
        assertEquals(expected, out);
    }
}
