/*
 * Copyright (c) 2005 Torbjšrn Gannholm
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 */
package net.homelinux.tobe.weffo;

import junit.framework.TestCase;

import javax.xml.transform.Result;
import javax.xml.transform.Source;
import javax.xml.transform.TransformerException;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;
import java.io.StringReader;
import java.io.StringWriter;

/**
 * Test the correctness of the transformation and weffo attributes.
 * The use of string comparisons is not perfect, and may fail for some implementations of parsers/transformers.
 */
public class TransformTest extends TestCase {
    String model = "<model test=\"Test\"><data>Value</data><type>String</type><repeat id=\"1\">first</repeat><repeat id=\"2\">second</repeat></model>";
    private final String weffoVersion = "1.1";

    public void testCopy() {
        String view = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<!-- comment --><?vi pi?>\n" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\" id=\"v\"><?v2 p2?>Text<child>Info<!-- data --></child></view>";
        String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<!--Generated by weffo version "+Weffo.VERSION+"-->" +
                "<!-- comment --><?vi pi?>\n" +
                "<view id=\"v\" xmlns:w=\"http://tobe.homelinux.net/weffo\"><?v2 p2?>Text<child>Info<!-- data --></child></view>";
        Source modelSource = new StreamSource(new StringReader(model));
        Source viewSource = new StreamSource(new StringReader(view));
        StringWriter result = new StringWriter();
        Result xslResult = new StreamResult(result);
        try {
            Weffo.outputFromPrototype(viewSource, modelSource, xslResult);
        } catch (TransformerException e) {
            e.printStackTrace();
        }
        String out = result.toString();
        assertEquals(expected, out);
    }

    public void testCopyNamespace() {
        String view = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<!-- comment --><?vi pi?>\n" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\" id=\"v\"><?v2 p2?>Text<child xmlns=\"http://mydom.org\">Info<!-- data --></child><o:child xmlns:o=\"http://yourdom.org\"/></view>";
        String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<!--Generated by weffo version "+Weffo.VERSION+"-->" +
                "<!-- comment --><?vi pi?>\n" +
                "<view id=\"v\" xmlns:w=\"http://tobe.homelinux.net/weffo\"><?v2 p2?>Text<child xmlns=\"http://mydom.org\">Info<!-- data --></child><o:child xmlns:o=\"http://yourdom.org\"/></view>";
        Source modelSource = new StreamSource(new StringReader(model));
        Source viewSource = new StreamSource(new StringReader(view));
        StringWriter result = new StringWriter();
        Result xslResult = new StreamResult(result);
        try {
            Weffo.outputFromPrototype(viewSource, modelSource, xslResult);
        } catch (TransformerException e) {
            e.printStackTrace();
        }
        String out = result.toString();
        assertEquals(expected, out);
    }

    public void testContent() {
        String view = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child w:text=\"/model/data\">Info<!-- data --></child></view>";
        String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<!--Generated by weffo version "+Weffo.VERSION+"-->" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child>Value</child></view>";
        Source modelSource = new StreamSource(new StringReader(model));
        Source viewSource = new StreamSource(new StringReader(view));
        StringWriter result = new StringWriter();
        Result xslResult = new StreamResult(result);
        try {
            Weffo.outputFromPrototype(viewSource, modelSource, xslResult);
        } catch (TransformerException e) {
            e.printStackTrace();
        }
        String out = result.toString();
        assertEquals(expected, out);
    }

    public void testForEach() {
        String view = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child w:foreach=\"/model/repeat\">Info</child></view>";
        String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<!--Generated by weffo version "+Weffo.VERSION+"-->" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child>Info</child><child>Info</child></view>";
        Source modelSource = new StreamSource(new StringReader(model));
        Source viewSource = new StreamSource(new StringReader(view));
        StringWriter result = new StringWriter();
        Result xslResult = new StreamResult(result);
        try {
            Weffo.outputFromPrototype(viewSource, modelSource, xslResult);
        } catch (TransformerException e) {
            e.printStackTrace();
        }
        String out = result.toString();
        assertEquals(expected, out);
    }

    public void testForEachContent() {
        String view = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child w:foreach=\"/model/repeat\" w:text=\".\">Info</child></view>";
        String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<!--Generated by weffo version "+Weffo.VERSION+"-->" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child>first</child><child>second</child></view>";
        Source modelSource = new StreamSource(new StringReader(model));
        Source viewSource = new StreamSource(new StringReader(view));
        StringWriter result = new StringWriter();
        Result xslResult = new StreamResult(result);
        try {
            Weffo.outputFromPrototype(viewSource, modelSource, xslResult);
        } catch (TransformerException e) {
            e.printStackTrace();
        }
        String out = result.toString();
        assertEquals(expected, out);
    }

    public void testDemo() {
        String view = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child w:demo=\"demo\">Info<!-- data --></child></view>";
        String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<!--Generated by weffo version "+Weffo.VERSION+"-->" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"/>";
        Source modelSource = new StreamSource(new StringReader(model));
        Source viewSource = new StreamSource(new StringReader(view));
        StringWriter result = new StringWriter();
        Result xslResult = new StreamResult(result);
        try {
            Weffo.outputFromPrototype(viewSource, modelSource, xslResult);
        } catch (TransformerException e) {
            e.printStackTrace();
        }
        String out = result.toString();
        assertEquals(expected, out);
    }

    public void testAttribute() {
        String view = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child w:attributes=\"data,/model/data\"/></view>";
        String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<!--Generated by weffo version "+Weffo.VERSION+"-->" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child data=\"Value\"/></view>";
        Source modelSource = new StreamSource(new StringReader(model));
        Source viewSource = new StreamSource(new StringReader(view));
        StringWriter result = new StringWriter();
        Result xslResult = new StreamResult(result);
        try {
            Weffo.outputFromPrototype(viewSource, modelSource, xslResult);
        } catch (TransformerException e) {
            e.printStackTrace();
        }
        String out = result.toString();
        assertEquals(expected, out);
    }

    public void testAttributes() {
        String view = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child w:attributes=\"data,/model/data;type,/model/type\"/></view>";
        String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<!--Generated by weffo version "+Weffo.VERSION+"-->" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child data=\"Value\" type=\"String\"/></view>";
        Source modelSource = new StreamSource(new StringReader(model));
        Source viewSource = new StreamSource(new StringReader(view));
        StringWriter result = new StringWriter();
        Result xslResult = new StreamResult(result);
        try {
            Weffo.outputFromPrototype(viewSource, modelSource, xslResult);
        } catch (TransformerException e) {
            e.printStackTrace();
        }
        String out = result.toString();
        assertEquals(expected, out);
    }

    public void testReplaceAttribute() {
        String view = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child data=\"Demo\" w:attributes=\"data,/model/data\"/></view>";
        String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<!--Generated by weffo version "+Weffo.VERSION+"-->" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child data=\"Value\"/></view>";
        Source modelSource = new StreamSource(new StringReader(model));
        Source viewSource = new StreamSource(new StringReader(view));
        StringWriter result = new StringWriter();
        Result xslResult = new StreamResult(result);
        try {
            Weffo.outputFromPrototype(viewSource, modelSource, xslResult);
        } catch (TransformerException e) {
            e.printStackTrace();
        }
        String out = result.toString();
        assertEquals(expected, out);
    }

    public void testComplexContent() {
        String view = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child w:content=\"/model\">Info<!-- data --></child></view>";
        String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<!--Generated by weffo version "+Weffo.VERSION+"-->" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child><model test=\"Test\"><data>Value</data><type>String</type><repeat id=\"1\">first</repeat><repeat id=\"2\">second</repeat></model></child></view>";
        Source modelSource = new StreamSource(new StringReader(model));
        Source viewSource = new StreamSource(new StringReader(view));
        StringWriter result = new StringWriter();
        Result xslResult = new StreamResult(result);
        try {
            Weffo.outputFromPrototype(viewSource, modelSource, xslResult);
        } catch (TransformerException e) {
            e.printStackTrace();
        }
        String out = result.toString();
        assertEquals(expected, out);
    }

    public void testNodesetContent() {
        String view = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child w:content=\"/model/node()\">Info<!-- data --></child></view>";
        String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<!--Generated by weffo version "+Weffo.VERSION+"-->" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child><data>Value</data><type>String</type><repeat id=\"1\">first</repeat><repeat id=\"2\">second</repeat></child></view>";
        Source modelSource = new StreamSource(new StringReader(model));
        Source viewSource = new StreamSource(new StringReader(view));
        StringWriter result = new StringWriter();
        Result xslResult = new StreamResult(result);
        try {
            Weffo.outputFromPrototype(viewSource, modelSource, xslResult);
        } catch (TransformerException e) {
            e.printStackTrace();
        }
        String out = result.toString();
        assertEquals(expected, out);
    }

    public void testText() {
        String view = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child w:text=\"/model\">Info<!-- data --></child></view>";
        String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                "<!--Generated by weffo version "+Weffo.VERSION+"-->" +
                "<view xmlns:w=\"http://tobe.homelinux.net/weffo\"><child>ValueStringfirstsecond</child></view>";
        Source modelSource = new StreamSource(new StringReader(model));
        Source viewSource = new StreamSource(new StringReader(view));
        StringWriter result = new StringWriter();
        Result xslResult = new StreamResult(result);
        try {
            Weffo.outputFromPrototype(viewSource, modelSource, xslResult);
        } catch (TransformerException e) {
            e.printStackTrace();
        }
        String out = result.toString();
        assertEquals(expected, out);
    }
}
